### ISSUE TITLE
How to run on Cityscapes?

### ISSUE THREAD

**Issue by Haochen-Wang409** [siyuhuang/TOD#5]
Hi, thanks for your work. However, this code seems to be only available on classification datasets. How can I run TOD on Cityscapes?

**Comment by siyuhuang** [comment]
Thanks for your question. The code for Cityscapes is not released. You could refer to https://github.com/fyu/drn and develop AL settings based on it.

**Comment by Haochen-Wang409** [comment]
OK, will it be released in the future?

**Comment by siyuhuang** [comment]
Probably not. It's a bit difficult to incorporate it into current repository.
